spring.application.name=school_docflow
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/enterprise_doc
spring.datasource.username=nikita
spring.datasource.password=qwerty

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
